- hosts: dvrax.com
  become: yes
  become_method: doas

  vars:
  - dns_name: dvrax.com

  tasks:
  - name: Make website folder
    file:
      path: "/var/www/{{ dns_name }}"
      mode: '0775'
      state: directory
      owner: www
      group: www

  - name: Make deployment user
    user:
      name: webdeploy
      groups: www

  - name: Enable httpd.
    service: name=httpd enabled=yes

  - name: Configure httpd with bootstrap config.
    template:
      src: templates/httpd_bootstrap.conf
      dest: /etc/httpd.conf

  - name: Reload httpd.
    service: name=httpd state=reloaded

  - name: Add acme domain configuration file.
    template:
      src: templates/acme-domain-client.conf
      dest: "/etc/acme/acme-client.{{ dns_name }}.conf"

  - name: Add acme provider configuration file.
    template:
      src: templates/acme-client-letsencrypt.conf
      dest: "/etc/acme/acme-client-letsencrypt.conf"

  - name: Include acme configuration files in /etc/acme-client.conf
    lineinfile:
      create: true
      path: /etc/acme-client.conf
      state: present
      line: "{{ item }}"
    loop:
    - 'include "/etc/acme/acme-client-letsencrypt.conf"'
    - 'include "/etc/acme/acme-client.{{ dns_name }}.conf"'

  - name: Get certificates.
    command: acme-client -v {{ dns_name }}
    args:
      creates: /etc/ssl/{{ dns_name }}.fullchain.pem 

  - name: Set up acme to run daily.
    lineinfile:
      path: /etc/daily.local
      line: "acme-client {{ dns_name }} && rcctl reload httpd"
      state: present
      create: yes

  - name: Configure httpd.
    template:
      src: templates/httpd.conf
      dest: /etc/httpd.conf

  - name: Reload httpd.
    service: name=httpd state=reloaded
